### ISSUE TITLE
Stability and performance issues

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#142]
The app is slow, and feels unreliable:

https://docs.google.com/document/d/1wb_ObYu-_3HRP5eRfVbybYwakUv3tJpjj2q_kuRIdQQ/edit

- Interface switches back and forth between "insufficient liquidity" and a price estimation
- In general slow: first load + selecting tokens + approve (Time from typing amount to seeing approve button)

**Comment by W3stside** [comment]
even in `production` or are you specifically talking about `dev`? @anxolin

**Comment by anxolin** [comment]
This refers to production. It's different to #153

**Comment by annamsgeorge** [comment]
In terms of speed performance: I think what came up most as user feedback was the long delay between the transaction having been executed (as shown on the GP Batch Explorer) versus how long it takes for the successful transaction to be indicated on the interface.

**Comment by anxolin** [comment]
The interface depends on an event from the node, if this is happening it can be:
- either we have a bug there, we will need to double check if that could be the case. I'd be a bit surprised, but possible
- or, the event notification doesn't happen, or is missed by the UI. Error with the connection or so on. 

If it's the second, then I'd consider changing how we wait for the trade to execute. Instead of using the blockchain, we can just use the API which would give us a consistent view of the system. Even in cases of reorgs, we have the same view as backend and explorer.

**Comment by annamsgeorge** [comment]
Ok interesting. I am not sure if the event is missed by the UI though since it does show up - but significantly later. I just stopped the time, there is a 40 seconds delay between the GP explorer showing the successful trade and the mooh sound + successful transaction pop up showing in the UI. 
This is in my view a big issue. Even though our transactions are fast, they seem to be very slow due to this delay in the interface.

**Comment by anxolin** [comment]
Closing, dealing in #261
