### ISSUE TITLE
It shows the notification of all your old orders on page load

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#186]
![image](https://user-images.githubusercontent.com/2352112/109540966-7c722980-7ac3-11eb-8cd2-9f24b031adf2.png)

When you open the UI, it shows sometimes the notifications of all the older orders. This was reported in the last user session we had last friday 26/02/2021. I think @W3stside has a hint what's the issue about

**Comment by alfetopito** [comment]
# Summary

This is what happens, as far as I can tell:

1. On every new block or account change, the app looks for trade events
2. Any new trade event is added to local storage
3. As a side effect, every new trade identified triggers a pop-up

When the app starts, if the orders were not checked before:
1. It starts from contract deployment block
2. Repeats `2` and `3` above

What's happening in this issue is either:
1. Local host was cleared
2. App is loaded in a new browser/domain (different app URL like a PR URL)

In those two cases, trade events are fetched from start and a pop-up is triggered for each.

**Comment by alfetopito** [comment]
A possible solution is to set a threshold of blocks difference to trigger pop-ups.

For example, only show a pop-up for events that occurred at most 50 blocks ago, compared against current block.

State update should remain unchanged, only pop-up behaviour is changed.

@anxolin @W3stside thoughts?

**Comment by anxolin** [comment]
Nice 🕵️‍♂️ job

> When the app starts, if the orders were not checked before:
> - It starts from contract deployment block

Why is that? We theoretically only need to check from last checked block. If there's no pending orders, we don't even need to check for new events. And when we send an order, maybe is wise to save the current block? (so if we leave, we know where to start looking for the trade)

**Comment by alfetopito** [comment]
> Why is that? We theoretically only need to check from last checked block. If there's no pending orders, we don't even need to check for new events. And when we send an order, maybe is wise to save the current block? (so if we leave, we know where to start looking for the trade)

The last block is stored every time it's checked.
The issue here is that the value isn't on local storage, thus it checks from the beginning of time.
