### ISSUE TITLE
Setup some basic QA workflow to start with

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#229]
Mareen and I talked to Liliya, the responsible person for QA in Gnosis Safe. We've got some insights from her work and process. 

One thing I would suggest to start doing for QA, is defining some small parts of this workflow.

One initial sketch could be:
- [x] Define templates, so we can use them as a base for new issues. We could review Gnosis Safe templates and adapt them to our projects
- [ ] Setup any tool we might need, even if the test cases are not fully defined, we can still track the version we are releasing, we might want to use it already? 
- [x] Add necessary columns in Zenhub for QA workflow. 
- [x] If there's a PR which would be good that QA get's to test in isolation before closing the release, is good to add her/him as reviewer, so it can be tested using the DEMO link that is in the PR. These PRs should have some context for the QA to help them understand what is to be tested.
- [x] Define how releases are done: The suggestion, we code freeze every 2 weeks. That version is tested by QA. All the issues are added to a report, in which we decide which one we fix before releasing, or which ones we document for fixing later.

Out of this issue, we could make a super short write down with the process, so it's explicitly defined.

Any feedback is welcomed. Mareen, do you think is good we start a small document for this and tackle the points?

cc/ @alfetopito @biocom @W3stside

**Comment by MareenG** [comment]
Thanks, yes it make sense to write it down. I started a small document [here](https://docs.google.com/document/d/1u_k5u4D2oGT9LjrCrBLIfN7FZSsre-EHMxdRIsKoHik/edit#) and am adding a few ideas to the different points

**Comment by anxolin** [comment]
@MareenG can we close this one? or maybe before we don, we can define some templates for our PRs and issues. We can use the Gnosis Safe PRs as a base

**Comment by MareenG** [comment]
I will finalize this today or on Monday and create the templates.

**Comment by MareenG** [comment]
Hey I have prepared(copied and adjusted) the templates but only could add them to my own replies. 
Does anyone have an idea how to add them to make them visible for all of us? 

**PR template for QA**
# Description

*High-level description of what your changes are accomplishing.*

# To Test
- [ ] Checkbox Style list of things a QA person could verify, i.e.
- [ ] Should display Text Input on our storybook
- [ ] Input should not accept Numbers
- [ ] new link should direct to the following URL

# Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*
*Optional: Include Mock ups for new designs*

**The Bug Template:** 

# Description
A clear and concise description of what the bug is.

# How to Reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error

# Behaviour
A clear and concise description of what is actually happening.

# Expected Behaviour
A clear and concise description of what you expected to happen.

# Screenshots/Videos
_optional_

# Notes
_optional:_ Other **important** information that would be useful to investigate the reported issue`

**Comment by alfetopito** [comment]
You can follow this guide https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Similar to what I shared from the CMM repo https://github.com/gnosis/safe-cmm-app-react/tree/development/.github/ISSUE_TEMPLATE

So, send a pull request with the templates to both repos (gp-ui and gp-swap-ui).

Let me know if you need any help :)
