### ISSUE TITLE
Issue with "valid to": Error 500 for duplicated orders

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#231]
If we send 2 times the same order, and we do it FAST, we will get an error from the backend (error `500`). 

![image](https://user-images.githubusercontent.com/2352112/110805556-7cbbb300-8281-11eb-862d-6d5044be8059.png)

This is because the ID is dependent on the hash of the order details.
I believe the cause of this issue is because we should at least change the `validTo` date, and we don't. `validTo` should be re-calculated in the second transaction (but it didn't happen)

**Comment by alfetopito** [comment]
This could be fixed while addressing https://github.com/gnosis/gp-swap-ui/issues/214

Although, this doesn't seem like a priority, given I don't expect many people want to send two identical orders in sequence. :shrug:

**Comment by alfetopito** [comment]
Got it.

Tx deadline comes from this hook https://github.com/gnosis/gp-swap-ui/blob/cf6389d8669cd1f8bad447bec922aed846d61d7a/src/hooks/useTransactionDeadline.ts#L8

Which updates the value when either:
- user updates their deadline
- there's a new block

So you'll get the issue above for every attempt to submit "identical" orders on the same block.

The simplest solution that I see is to rely on browser's timestamp instead of block timestamp.
This could be an issue in case the user has (on purpose or not) set their clock in the past, potentially creating invalid `validTo`.
