### ISSUE TITLE
Fix false notifications

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#258]
# Description
I got two notifications for the same trade. The first one stated I swapped 0 DAI for  0USDC. Shortly after I received the correct notification. 

# To Reproduce:
Normal trading process

# Expected Behaviour
Only one trading notification with the correct values

# Actual Behaviour
- See description and screenshot
- So far I only experienced this once

# Screenshots/Videos
![Bildschirmfoto 2021-03-17 um 10 02 02](https://user-images.githubusercontent.com/34510341/111445229-7eff9080-870b-11eb-8478-5cf6094c83cf.png)
![Bildschirmfoto 2021-03-17 um 10 01 55](https://user-images.githubusercontent.com/34510341/111445232-7f982700-870b-11eb-99fb-45b25980ca2d.png)

# More info
https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0xf19d12279e587007f1dd9759ba723b1e83f945682e8e0f0d3a415c20f1abf47b52df85e9de71aa1c210873bcf37ec46d36c99dc26051c9db

**Comment by anxolin** [comment]
We should take a look soon to this one. 
Anna reported something similar (she heard the cow twice)

cc/ @W3stside

**Comment by alfetopito** [comment]
After 2 tries without issues, the `0` msg appeared on the third try.
Nothing special about the third try AFAICT

Orders:
1. https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x7e4bf4578f214d1b90e89dfd70f3c59bbd8e24d873e1b69d24faab4741c507c55b0abe214ab7875562adee331deff0fe1912fe42605cf7eb
2. https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x52407901210bfc28ff6faf2534d429ec74276bb8da1b3a82ff54cae2cbad059b5b0abe214ab7875562adee331deff0fe1912fe42605cf887
3. https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x15f91e6d2a464278d16d88ddabd353cdd2fc4a575ba342757cf907d82293da4f5b0abe214ab7875562adee331deff0fe1912fe42605cfb16

![screenshot_2021-03-25_14-03-53](https://user-images.githubusercontent.com/43217/112543592-35e6b680-8d73-11eb-9b1f-98185a50bf76.png)

Still investigating...

**Comment by alfetopito** [comment]
After tens of tries, got it again.
This time I have some more logs, and I narrowed it down to the API response:

![screenshot_2021-03-25_15-41-39](https://user-images.githubusercontent.com/43217/112552804-9fb98d00-8d80-11eb-837c-e98927456a33.png)
 Executed amounts are `0`

Here's the order in question https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0xaa8c74afc92c8ecfaecbc01f59f293909a508201412b1b7cb32d5f544baca7fe5b0abe214ab7875562adee331deff0fe1912fe42605d11c4

That's an issue because we count on API data to create the pop up contents when an api response is available:
https://github.com/gnosis/gp-swap-ui/blob/393fc30eab1cf77a85d7822d716a1a4fb9190129/src/custom/state/orders/updater.ts#L50-L60

API response for reference:

```json
{
  "creationDate": "2021-03-25T22:39:04.590804Z",
  "owner": "0x5b0abe214ab7875562adee331deff0fe1912fe42",
  "uid": "0xaa8c74afc92c8ecfaecbc01f59f293909a508201412b1b7cb32d5f544baca7fe5b0abe214ab7875562adee331deff0fe1912fe42605d11c4",
  "availableBalance": "400676315775725995",
  "executedBuyAmount": "0",
  "executedSellAmount": "0",
  "executedSellAmountBeforeFees": "0",
  "executedFeeAmount": "0",
  "invalidated": false,
  "sellToken": "0xc778417e063141139fce010982780140aa0cd5ab",
  "buyToken": "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
  "sellAmount": "99899999999900000",
  "buyAmount": "851505182963152901",
  "validTo": 1616712132,
  "appData": 0,
  "feeAmount": "100000000100000",
  "kind": "sell",
  "partiallyFillable": false,
  "signature": "0xce5230678edffd3e74fc17861d637a417706f1539aa6674e9b1f2b8effd43e2f5ddc926d2be3fc2f0be3d431f3d38e6237bd75fa590faae5bd0824b5f81abe721c"
}
```

**Comment by anxolin** [comment]
Awesome 🕵️‍♀️ job

I think for several reasons that we should change the "event" approach for a API approach in how we detect the trade was executed. Basically, same as in the Explorer. 

Reasons are:
- We've been reported that sometimes we don't even notify the success. 
- This way we get the same view as the explorer and the API, so the apps are more coherent
- It feels more solid the API than the different web3 connections. Less decentralize yes, but we depend fully on the API anyways, so it won't make a difference.

My understanding of what we should do is:
* [ ] Do periodic polling every few seconds while we wait for an order to be executed
* [ ] When is executed (amount > 0) then we notify and change the state
* [ ] Additionally we can still leave the watching of the Ethereum Event. If we receive the event, we eagerly check the API in case the API is already aware of the execution. If the API returns `amount=0`, then we just ignore that and wait for the next poll

**Comment by alfetopito** [comment]
Agreed, we should use the API as source of truth.

BUT, I have a quick fix we can do if we want, which would solve the `0` values. Although that'll show estimated rather than the precise estimation values...
TBH, that's already what's in place, but it's not checking for the correct that.

Here's the fallback message, which is the same as the original swap notification: https://github.com/gnosis/gp-swap-ui/blob/393fc30eab1cf77a85d7822d716a1a4fb9190129/src/custom/state/orders/updater.ts#L45

Then, if there's a response from the api, we try to create a new one https://github.com/gnosis/gp-swap-ui/blob/393fc30eab1cf77a85d7822d716a1a4fb9190129/src/custom/state/orders/updater.ts#L49

But we should additionally check if the executed values are `0`.

What do you think? Quick fix then proper fix, or just quick fix, or just proper fix?
I'm inclined to do both.

**Comment by alfetopito** [comment]
@MareenG should be fixed in dev. Could you try it out?

**Comment by MareenG** [comment]
Yes, It should be fixed. Didin't encounter this error anymore
