### ISSUE TITLE
Transanctions in GP never fail

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#266]
In GP, from the user's point of view. The tx don't fail

We already adapted the tooltips, but we need to adapt also these messages:
![image](https://user-images.githubusercontent.com/2352112/111480786-a3229800-8732-11eb-8306-7369d7ae25a1.png)

**Comment by W3stside** [comment]
@anxolin @alfetopito @bh2smith 

Wondering what to do with this message:
![Screenshot from 2021-04-07 13-32-54](https://user-images.githubusercontent.com/21335563/113866919-ca0a4200-97a5-11eb-805b-79ef4a8ffcb3.png)

@bh2smith mentioned it is something to consider changing/removing but should be discussed. leaving here for now

**Comment by bh2smith** [comment]
Because there will be DAO rules in place preventing solvers from front running this kind of thing, it would make sense to remove. In the beginning the silver list will be centrally curated so we can be sure that this won't happen. However, the more that I think about it, the more I suspect we will have a difficult time defining slashing criteria that can accurately detect when such a scenario has occurred. 

In the future I would think that we should not allow slippage to be so high. Maybe max out at 10%.

**Comment by bh2smith** [comment]
Although solvers who are continually underperforming in terms of objective value (Ie those front running, should be slashed). Only thing I am not sure of is that front running these high slippages would easily be reflected as an underperforming solver in any way.

**Comment by fleupold** [comment]
I think we should remove this message. Our solver will chose a much smaller slippage for the actual on-chain transaction (this slippage here only applies to offchain price calculation) and therefore the user cannot be front-run to the same degree as Uniswap.

Since this is also one of our main selling points, we shouldn't scare users with a message like that.
