### ISSUE TITLE
Error signing transactions with Ledger

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#324]
Error using ledger to sign tx

**Comment by alfetopito** [comment]
Started fresh with a new ledger ETH account on rinkeby.
- Wrapped ETH https://rinkeby.etherscan.io/tx/0x89abe5a289b4ef7acf191d9bc8a6e72318fb8816538483ddb7cabbd5746d16d7
- Approved WETH https://rinkeby.etherscan.io/tx/0x6040cb16d3be61d5ee0cc214b86163df2cdb3ef9aef7e9255244d0a2fb1ae25d

When the times comes to swap though, it fails when it was supposed to show the MM modal
![screenshot_2021-04-05_14-07-30](https://user-images.githubusercontent.com/43217/113627392-4c64fb80-9618-11eb-9141-03e84bc53f66.png)
![screenshot_2021-04-05_14-08-40](https://user-images.githubusercontent.com/43217/113627445-630b5280-9618-11eb-9f4f-27131cca1011.png)

**Comment by alfetopito** [comment]
Seems like this is not yet supported on MM https://github.com/MetaMask/metamask-extension/issues/10240
We might need to wait on them to release Ledger signature support.

**Comment by alfetopito** [comment]
The Safe uses multiple approaches to perform the signing https://github.com/gnosis/safe-react/blob/8b35069e15e970dd8e27c9d44f527e3cd001c4a1/src/logic/safe/transactions/offchainSigner/index.ts
GPv2 contract also supports different signing methods https://github.com/gnosis/gp-v2-contracts/blob/19de022dd0c1c01cb0b1c5b3175528f2a6ced811/src/ts/sign.ts#L36

I'll see whether I it's possible to create a workaround using a different signing scheme.

**Comment by alfetopito** [comment]
# Summary of research so far
- MM currently doesn't support Ledger EIP712 signatures (MetaMask/metamask-extension#10240)
- The combination of https://github.com/gnosis/gp-v2-contracts/pull/580 and https://github.com/gnosis/gp-swap-ui/pull/387 offers a work around, where ETHSIGN is used instead.

# First solution
This solution has the downside that the signed data is opaque, meaning the user doesn't see the fields that are being signed.

Other downside (or upside, depending how you see it) is that we can't initially tell whether the address from MM is a hardware wallet, we first show the regular order sign modal, and when user tries and fails to sign that, the second hash sign modal is displayed.

The downside here is that the first modal will always fail (we can cache this and only show this once).

The possible upside is that the first modal has the full details and might be useful.

## First modal example
![screenshot_2021-04-07_13-47-24](https://user-images.githubusercontent.com/43217/114091009-fb9a1080-986c-11eb-9a2c-5336f6db2a5b.png)

## Second modal example
![screenshot_2021-04-07_13-48-19](https://user-images.githubusercontent.com/43217/114091028-005ec480-986d-11eb-931e-4f638bee6e6f.png)

I think we need to get user input on this behaviour.

# Second solution
A second approach for Ledger users is to add ledger support directly, like the Safe does
![screenshot_2021-04-08_13-22-30](https://user-images.githubusercontent.com/43217/114091444-8da21900-986d-11eb-9d69-f13a50738530.png)

I have integrated the library locally and was able to place and order using ETHSIGN signature method without much effort.
The caveat here is that it isn't possible to pick the Ledger account. Only the first default derivated address is selected:
![screenshot_2021-04-08_11-16-50](https://user-images.githubusercontent.com/43217/114091654-cb06a680-986d-11eb-8c7e-55dad78b8c62.png)

To do that, I believe will require a few more days worth of effort, since we require some sort of modals like what the Safe offers:

## Chose derivation path
![screenshot_2021-04-08_12-56-44](https://user-images.githubusercontent.com/43217/114091830-0012f900-986e-11eb-97cc-8f97804a1ea6.png)

## Chose account
![screenshot_2021-04-08_12-55-58](https://user-images.githubusercontent.com/43217/114091818-fc7f7200-986d-11eb-8226-48038a8c8db6.png)

**Comment by alfetopito** [comment]
Important thing to note.
I was signing a tx in my Safe with a Ledger connected through Metamask, and I noticed the behaviour is *exactly* like `solution 1`.
First a modal with message details. The another to sign the hash.
