### ISSUE TITLE
Cow game

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#351]
Evaluate if we want to do a cow game, and how would it be:

https://github.com/wayou/t-rex-runner

**Comment by annamsgeorge** [comment]
Definitely :D :D 

Here are pixelated cows from shutterstock that we could use: https://www.shutterstock.com/search/cow+pixel

Maybe this one: https://www.shutterstock.com/de/image-vector/white-spotted-milk-cow-pixel-art-1481815034 or this one https://www.shutterstock.com/de/image-vector/vector-illustration-cartoon-cow-pixel-design-387937882


And instead of cacti that it has to jump over, we use sandwiches:

Shutterstock also has a bunch of pixelated sandwiches, for example: https://www.shutterstock.com/de/image-vector/pixel-art-food-sandwich-contains-penance-1889485303

**Comment by anxolin** [comment]
Internal notes for meeting. Review these tasks:
GAME:
* Sprites: @biocom 
* Wireframes: @biocom  (+ @anxolin  )
* Modal / game inside the confirmation modal: lets wait for the wireframes
* Fork project + add custom sprites: @anxolin
* NPM package????> @anxolin
* Component that consumes NPM package? → @anxolin
* Loader if is too slow?

Notes for other fun games: Flappy birds version was also a nice option
