### ISSUE TITLE
UI has a long delay before showing successful execution 

### ISSUE THREAD

**Issue by annamsgeorge** [gnosis/gp-swap-ui#352]
There is a significant time delay (40 seconds) between the GP explorer showing that a transaction was successfully executed and the interface showing it. In other words: only 40 seconds after the trade has already been executed the mooh sound comes up and the top right window pops up saying your transaction was successful.

**Comment by anxolin** [comment]
This is likely from a part lendro is touching, so I think will be addressed with that. 

@alfetopito basically we would need to kill the delay. https://github.com/gnosis/gp-swap-ui/blob/393fc30eab1cf77a85d7822d716a1a4fb9190129/src/custom/state/orders/updater.ts#L215 I think this part was created to avoid race conditions, but the problem with these ones affects experiation, not success. So i think is weird we added it there. I think anyways, I think will be solved once we do the new approach of polling from the API and only using the events to cut time in the polling interval (as a trigger)

**Comment by alfetopito** [comment]
Potentially closed by https://github.com/gnosis/gp-swap-ui/pull/354

**Comment by MareenG** [comment]
It is now super fast for the executed trades. 
CowSwap is now faster than the explorer. 
For the expired orders there is still a 40 sec delay. 
I think this isn't a big issue. It is also an improvement before for some expired orders it sometimes took several min until it was shown in the cow UI.

**Comment by anxolin** [comment]
We leave some time before we announce the user that the order is expired. This is because it can still be executed in a block that we learn about seconds after the expiration. We actually wait 45seconds because it's 3 block confirmations.
This accounts for reorgs, and for the inexact nature of bock time. 

If it makes bad UX we can wait just 15seconds. We would risk sometimes getting a failed tx together with a successful one, but maybe it doesn't happen to often and the UX is better. Should we try it out?

**Comment by MareenG** [comment]
I think we can stick to the longer waiting time having a failed  transaction in the UI eventhough it went through is a bad UX, imo. Also 45s is not that long.

**Comment by MareenG** [comment]
I would close this issue. If we get user feedback we could consider to only wait for 15s.
